---
- name: Remove mods
  become: yes
  become_user: "{{ vertx_user }}"
  become_method: su
  with_dict: "{{ mods }}"
  file: path="{{ springboard_path }}/mods/{{ item.value.prefix }}~{{ item.key }}~{{ item.value.version }}" state=absent

- name: Remove jars
  become: yes
  become_user: "{{ vertx_user }}"
  become_method: su
  with_dict: "{{ mods }}"
  file: path="{{ springboard_path }}/mods/{{ item.value.prefix }}~{{ item.key }}~{{ item.value.version }}-fat.jar" state=absent

- name: Copy local mods
  with_dict: "{{ mods }}"
  copy:
    src: "{{ item.value.location }}/build/libs/{{ item.value.prefix }}~{{ item.key }}~{{ item.value.version }}-fat.jar"
    dest: "{{ springboard_path }}/mods"
    owner: "{{ vertx_user }}"
    group: "{{ vertx_group }}"
  when: item.value.location is defined

- name: Copy build mods
  with_dict: "{{ mods }}"
  copy:
    src: "{{ playbook_dir }}/workspace/{{ inventory_hostname }}/{{ item.key }}/build/libs/{{ item.value.prefix }}~{{ item.key }}~{{ item.value.version }}-fat.jar"
    dest: "{{ springboard_path }}/mods"
    owner: "{{ vertx_user }}"
    group: "{{ vertx_group }}"
  when: item.value.location is not defined  
...